---
swagger: '3.0'
basePath: "/api/fdna_reporting"
schemes:
- https
info:
  version: 1.0.0
  title: Commercial Fleet Vehicle Operating Data
  description: |-
    Query our database of commercial fleet vehicle operating data for medium and heavy-duty vehicles. The data available consists of drive-cycle metrics across trips that characterize vehicle operating behavior. Data is grouped by vehicle day, which consists of a 24-hour period of operation.

    Fleet DNA consists of high resolution vehicle operation data that NREL collects from fleets around the country. The data are processed using a standard processing routine, and the aggregated results of each study are cleansed of personally identifying information.

    This API was originally developed to support the <a href="https://www.nrel.gov/transportation/fleettest-fleet-dna.html">Fleet DNA Clearinghouse</a>, where visualizations of the data and more information can be found.

    A <a href="https://www.nrel.gov/docs/fy14osti/62572.pdf">Fleet DNA Data Dictionary</a> is available and is especially helpful for identifying data fields of interest via the /results_days endpoint

    Suggested workflow:
    &#8226; Identify vehicle type id of interest via the /vehicle_types endpoint
    &#8226; Identify data fields of interest via the /results_days endpoint (use data dictionary for explanation of fields)
    &#8226; Gather data by sending request to the /results_days/{vehicle_type_id} endpoint with data fields of interest specified as col[] parameters
paths:
  "/v1/afdc_summaries":
    get:
      responses:
        '200':
          description: Successful request
          schema:
            "$ref": "#/definitions/DataSummary"
      description: ''
      summary: Return a summary of the complete dataset.
      parameters:
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
  "/v1/vehicle_types":
    get:
      responses:
        '200':
          description: Successful request
          schema:
            "$ref": "#/definitions/VehicleTypes"
      description: ''
      summary: Return a list of commercial vehicle types. There are 39 total vehicle types. This endpoint is helpful for specifying the vehicle type for the /results_days/{vehicle_type_id} endpoint below.
      parameters:
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
  "/v1/results_days":
    get:
      responses:
        '200':
          description: Successful request
          schema:
            "$ref": "#/definitions/ResultsDaysDataFields"
      description: ''
      summary: Return a list of available data fields. These data fields can then be specified as parameters for the /results_days/{vehicle_type_id} endpoint below. There are 350 data fields to choose from.
      parameters:
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
  "/v1/results_days/{vehicle_type_id}":
    get:
      responses:
        '200':
          description: Successful request
          schema:
            "$ref": "#/definitions/ResultsDays"
      description: ''
      summary: Return a series of daily specified values (via the col[] parameters) for a specified vehicle type.
      parameters:
      - in: path
        description: Vehicle type id
        name: vehicle_type_id
        required: true
        type: string
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
      - in: query
        description: |-
          List of data fields to be retrieved. Multiple values can be specified (this parameter is an array).  The options for the data fields to be retrieved are specified in the <a href='https://www.nrel.gov/docs/fy14osti/62572.pdf'>Fleet DNA Data Dictionary</a>. In addition to the fields in the data dictionary, users can specify the following fields:
            + deployment.vehicle_class_id,
            + deployment.vocation_id,
            + deployment.vehicle_type_id,
            + deployment.drivetrain_id,
            + deployement.fuel_type_id
        name: col[]
        enum: [deployments.pid, deployments.vocation_id, results_days.total_average_speed, results_days.kinetic_intensity, results_days.vehicle_id]
        required: true
        type: string
        default: results_days.kinetic_intensity
definitions:
  Metadata:
    properties:
      version:
        type: string
        description: This is the version of the api
    example:
      version: "1.0.0"
  DataSummary:
    required:
    - metadata
    - result
    properties:
      metadata:
        "$ref": "#/definitions/Metadata"
      result:
        description: Summary of commercial vehicle dataset
        required:
          - average_speed_average
        properties:
          average_speed_average:
            type: integer
            description: Avg. of vehicles' avg. speeds
            example: 15
          average_speed_min:
            type: integer
            description: Min. of vehicles' avg. speeds
            example: 0
          average_speed_max:
            type: integer
            description: Max. of vehicles' avg. speeds
            example: 64
          max_speed_average:
            type: integer
            description: Avg. of vehicles' max. speeds
            example: 60
          max_speed_min:
            type: integer
            description: Min. of vehicles' max. speeds
            example: 19
          max_speed_max:
            type: integer
            description: Max. of vehicles' max. speeds
            example: 100
          distance_average:
            type: integer
            description: Avg. of vehicles' distances traveled
            example: 72
          distance_min:
            type: integer
            description: Min. of vehicles' distances traveled
            example: 1
          distance_max:
            type: integer
            description: Max. of vehicles' distances traveled
            example: 679
          operating_time_average:
            type: integer
            description: Avg. of vehicles' operating times
            example: 5
          stops_average:
            type: integer
            description: Avg. of vehicles' stops
            example: 122
          stops_per_mile_average:
            type: integer
            description: Avg. of vehicles' stops per mile
            example: 2
          total_days:
            type: integer
            description: Summation of all vehicles' days during study
            example: 6742
          total_vehicles:
            type: integer
            description: Count of vehicles involved in study
            example: 533
  VehicleTypes:
    required:
    - metadata
    - result
    properties:
      metadata:
        "$ref": "#/definitions/Metadata"
      result:
        description: List of vehicle types available
        type: array
        items:
          required:
          - id
          - description
          properties:
            id:
              type: integer
              description: Unique id of vehicle type
              example: 5
            description:
              type: string
              description: Vehicle type
              example: "City Transit Bus"
  ResultsDays:
      required:
      - metadata
      - inputs
      - result
      properties:
        metadata:
          "$ref": "#/definitions/Metadata"
        inputs:
          description: List of request inputs
          type: array
          example:
            - vehicle_type_ids: [31]
            - columns: [results_days.vehicle_id, deployments.pid, deployments.vocation_id, results_days.kinetic_intensity, results_days.total_average_speed]
            - format: json
        result:
          type: array
          items:
            type: object
            properties:
              vehicle_id:
                type: integer
              pid:
                type: integer
              vocation_id:
                type: integer
              kinetic_intensity:
                type: integer
              total_average_speed:
                type: integer
          example:
            - vehicle_id: 112
              pid: 3
              vocation_id: 4
              kinetic_intensity: 3.22199934474104
              total_average_speed: 7.32241918206163
            - vehicle_id: 112
              pid: 3
              vocation_id: 4
              kinetic_intensity: 2.58558724559133
              total_average_speed: 9.28415509409981
  ResultsDaysDataFields:
    required:
    - metadata
    - results
    properties:
      metadata:
        "$ref": "#/definitions/Metadata"
      result:
        type: array
        items:
          type: string
        example:
          - deployments.nda
          - results_days.vehicle_id
          - results_days.deployment_id
          - deployments.pid
          - deployments.vehicle_class_id
          - deployments.vocation_id
          - deployments.vehicle_type_id
          - deployments.drivetrain_id
          - deployments.fuel_type_id
          - results_days.day_id
          - results_days.trip_count
          - results_days.mt_count
          - results_days.start_ts
          - results_days.end_ts
          - results_days.start_rts
          - results_days.end_rts
