---
swagger: '2.0'
host: "devstage.nrel.gov"
basePath: "/api/fdna_reporting"
schemes:
- https
securityDefinitions:
  ApiKeyQueryAuth:
    type: apiKey
    in: query
    name: api_key
  ApiKeyHeaderAuth:
    type: apiKey
    in: header
    name: X-Api-Key
security:
  - ApiKeyQueryAuth: []
  - ApiKeyHeaderAuth: []
info:
  version: 1.0.0
  title: Commercial Fleet Vehicle Operating Data
  description: |-
    Query our database of commercial fleet vehicle operating data for medium and heavy-duty vehicles. The data available consists of drive-cycle metrics across trips that characterize vehicle operating behavior. Data is grouped by vehicle day, which consists of a 24-hour period of operation.

    Fleet DNA consists of high resolution vehicle operation data that NREL collects from fleets around the country. The data are processed using a standard processing routine, and the aggregated results of each study are cleansed of personally identifying information.

    This API was originally developed to support the <a href="https://www.nrel.gov/transportation/fleettest-fleet-dna.html">Fleet DNA Clearinghouse</a>, where visualizations of the data can be found.

    A <a href="https://www.nrel.gov/docs/fy14osti/62572.pdf">Fleet DNA Data Dictionary</a> is available and is especially helpful for identifying data fields of interest via the /results endpoint
paths:
  "/v1/afdc_summaries":
    get:
      responses:
        '200':
          description: Successful request
          schema:
            "$ref": "#/definitions/DataSummary"
      description: ''
      summary: Return a summary of the complete dataset.
  "/v1/vehicle_days":
    get:
      responses:
        '200':
          description: Successful request
          schema:
            "$ref": "#/definitions/Results"
      description: ''
      summary: Return drive-cycle metrics grouped by vehicle day. Results can be queried by city of vehicle depot, state of vehicle depot, vehicle class, vehicle type, drivetrain, fuel type, and vocation.
      parameters:
      - in: query
        description: Drive-cycle metrics to be returned. There are over 350 metrics available to choose from. If none are specified, all of the metrics for a given vehicle day will be returned. A <a href="https://www.nrel.gov/docs/fy14osti/62572.pdf" target="_blank">Data Dictionary</a> is available which contains a complete list of metrics and their descriptions.
        name: metrics
        required: false
        type: array
        items:
          type: string
      - in: query
        description: Vehicle classes to query by
        name: vehicle_classes
        required: false
        type: array
        items:
          type: string
          enum: ["Class1", "Class2", "Class3", "Class4", "Class5", "Class6", "Class7", "Class8"]
      - in: query
        description: Vehicle types to query by
        name: vehicle_types
        required: false
        type: array
        items:
          type: string
          enum: ["Beverage", "BucketTruck", "CementMixer", "CityDelivery", "CityTransitBus", "ConventionalVan", "CrewSizePickup", "DumpTruck", "FireTruck", "Fuel", "FullSizePickup", "Furniture", "HeavySemiTractor", "HighProfileSemi", "HomeFuel", "LandscapeUtility", "MediumSemiTractor", "MiniBus", "MiniPickup", "Minivan", "Rack", "RefrigeratedVan", "RefuseTruck", "SUV", "SchoolBus", "SemiSleeper", "ServiceVan", "SingleAxleVan", "StakeBody", "StepVan", "StraightTruck", "TourBus", "TowTruck", "Tractor", "TypeC", "UtilityVan", "WalkIn"]
      - in: query
        description: Vehicle drivetrains to query by
        name: drivetrains
        required: false
        type: array
        items:
          type: string
          enum: ["Conventional", "Electric", "Hybrid", "HybridEV", "HybridElectric", "HydraulicHybrid", "ParallelHybrid", "SeriesHybrid"]
      - in: query
        description: Vehicle fuel types to query by
        name: fuel_types
        required: false
        type: array
        items:
          type: string
          enum: ["CNG", "Diesel", "Electricity", "Gasoline", "HEV"]
      - in: query
        description: Vehicle vocations to query by
        name: vocations
        required: false
        type: array
        items:
          type: string
          enum: ["BeverageDelivery", "FoodDelivery", "FoodDistribution", "GroceryDelivery", "LinenDelivery", "LocalDelivery", "LongHaul", "MassTransit", "ParcelDelivery", "Personal", "PortDrayage", "RefusePickup", "SchoolBus", "SnowPlow", "Telecom", "Towing", "Utility", "WarehouseDelivery"]
definitions:
  Metadata:
    properties:
      version:
        type: string
        description: This is the version of the api
    example:
      version: "1.0.0"
  Inputs:
    properties:
      inputs:
        type: object
        description: Parameters specified in the request
        example:
          vehicle_types: FullSizePickup,MiniPickup
          drivetrains: Diesel
          metrics: max_speed,kinetic_intensity
  Results:
    properties:
      metadata:
        "$ref": "#/definitions/Metadata"
      inputs:
        "$ref": "#/definitions/Inputs"
      daily_results:
        type: array
        items:
          type: object
        example:
          - max_speed: 74.8248511904762
            kinetic_intensity: 0.459176722131882
            vehicle_type: Tractor
            vehicle_class: Class 7
            vocation: Beverage Delivery
            drivetrain: Conventional
            fuel_type: Diesel
          - max_speed: 58.195928885256
            kinetic_intensity: 0.64974190558627
            vehicle_type: Refuse Truck
            vehicle_class: Class 8
            vocation: Refuse Pickup
            drivetrain: Conventional
            fuel_type: CNG
  DataSummary:
    required:
    - metadata
    - inputs
    - result
    properties:
      metadata:
        "$ref": "#/definitions/Metadata"
      inputs:
        "$ref": "#/definitions/Inputs"
      result:
        description: Summary of commercial vehicle dataset
        required:
          - average_speed_average
        properties:
          average_speed_average:
            type: integer
            description: Avg. of vehicles' avg. speeds
            example: 15
          average_speed_min:
            type: integer
            description: Min. of vehicles' avg. speeds
            example: 0
          average_speed_max:
            type: integer
            description: Max. of vehicles' avg. speeds
            example: 64
          max_speed_average:
            type: integer
            description: Avg. of vehicles' max. speeds
            example: 60
          max_speed_min:
            type: integer
            description: Min. of vehicles' max. speeds
            example: 19
          max_speed_max:
            type: integer
            description: Max. of vehicles' max. speeds
            example: 100
          distance_average:
            type: integer
            description: Avg. of vehicles' distances traveled
            example: 72
          distance_min:
            type: integer
            description: Min. of vehicles' distances traveled
            example: 1
          distance_max:
            type: integer
            description: Max. of vehicles' distances traveled
            example: 679
          operating_time_average:
            type: integer
            description: Avg. of vehicles' operating times
            example: 5
          stops_average:
            type: integer
            description: Avg. of vehicles' stops
            example: 122
          stops_per_mile_average:
            type: integer
            description: Avg. of vehicles' stops per mile
            example: 2
          total_days:
            type: integer
            description: Summation of all vehicles' days during study
            example: 6742
          total_vehicles:
            type: integer
            description: Count of vehicles involved in study
            example: 533
